AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
Documentation:
    Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Max: 10
Metrics/ClassLength:
  Max: 100
# TODO: Add proper error handling
Style/RescueStandardError:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
